routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@getIndex');
Route::get('about', 'PagesController@getAbout');
Route::get('contact', 'PagesController@getContact');
Route::get('view', 'PagesController@getView');
Route::resource('listing', 'ListingController');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/view/listing/{id}','PagesController@viewListing')->name('front.view.listing');

Route::group(['prefix'=>'admin','namespace'=>'Admin'],function(){
    
    Route::get('/login','LoginController@showLoginForm')->name('admin.get.loginForm');
    Route::post('/login','LoginController@login')->name('admin.login');
    Route::post('/logout','LoginController@logout')->name('admin.logout');

    Route::get('/dashboard','DashboardController@index')->name('admin.dashboard');

    Route::group(['prefix'=>'listings'],function(){
        Route::get('/index','ListingController@index')->name('admin.listings');
        Route::get('/show/{id}','ListingController@show')->name('admin.view.listings');
        Route::get('/create','ListingController@create')->name('admin.create.listings');
        Route::post('/store','ListingController@store')->name('admin.store.listings');
        Route::get('/edit/{id}','ListingController@edit')->name('admin.edit.listings');
        Route::post('/update/{id}','ListingController@update')->name('admin.update.listings');
        Route::post('/destroy/{id}','ListingController@destroy')->name('admin.destroy.listings');
    });


    Route::group(['prefix'=>'listings-category'],function(){
        Route::get('/index','ListingCategoryController@index')->name('admin.listings-cat');
        Route::post('/store','ListingCategoryController@store')->name('admin.store.listings-cat');
        Route::post('/update/{id}','ListingCategoryController@update')->name('admin.update.listings-cat');
        Route::post('/destroy/{id}','ListingCategoryController@destroy')->name('admin.destroy.listings-cat');
    });
});

app/listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class listing extends Model
{
    // protected $fillable = [
    //     'name','location','bathroom','bedroom','area','garage','description','cooling','map','price','photo',
    // ];
    protected $guarded = [];
}

app/Http/Controllers/Admin/ListingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\listing as Listing;
use App\ListingCategory;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;

class ListingController extends Controller
{

    public function __construct()
    {
        $this->middleware('admin');
        $this->storage = Storage::disk('listings');
    }


    public function index()
    {
        $listings = Listing::all();
        return view('admin.listings.index',['listings'=>$listings]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = ListingCategory::all();
        return view('admin.listings.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateListingsArray($request);
        $this->validate($request,[
            'photo'=>'required|file'
        ]);

        try {
            $filename = null;

            if($request->hasfile('photo') && $request->file('photo')->isValid()){
                $filename = $this->storage->putFile('',$request->file('photo'));
               
            }else{
                throw new \Exception(' You need to put a valid image to proceed');
            }

            $data = [
                'name' => $request->input('name'),
                'location' => $request->input('location'),
                'bathroom' => $request->input('bathroom'),
                'bedroom' => $request->input('bedroom'),
                'area' => $request->input('area'),
                'description' => $request->input('description'),
                'cooling' => $request->input('cooling'),
                'price' => $request->input('price'),
                'photo' => $filename,
                'status' => $request->input('status'),
                'category_id' => $request->input('category_id')
            ];
            Listing::forceCreate($data);
        } catch (\Exception $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }
        return redirect()->back()->with('success', ' Listing successfully added');
    }

    public function validateListingsArray($request)
    {
        $request->validate([
            'name' => 'required',
            'location' => 'required',
            'bathroom' => 'required',
            'bedroom' => 'required',
            'area' => 'required',
            'description' => 'required',
            'cooling' => 'required',
            'price' => 'required|integer',
            'category_id' => 'required'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $listing = Listing::find($id);

        return view('admin.listings.show', ['listing' => $listing]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $listing = Listing::find($id);
        $categories = ListingCategory::all();
        return view('admin.listings.edit', ['listing' => $listing,'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
        //
        $this->validateListingsArray($request);
    
        try {
            $listing = Listing::find($request->id);
            $data = [
                'name' => $request->input('name'),
                'location' => $request->input('location'),
                'bathroom' => $request->input('bathroom'),
                'bedroom' => $request->input('bedroom'),
                'area' => $request->input('area'),
                'description' => $request->input('description'),
                'cooling' => $request->input('cooling'),
                'price' => $request->input('price'),
                'status' => $request->input('status'),
                'category_id' => $request->input('category_id')
            ];
           
            
            $listing->update($data);
            if($request->hasfile('photo') && $request->file('photo')->isValid()){
                $filename = $this->storage->putFile('',$request->file('photo'));
                $this->storage->delete($listing->photo);
                $listing->update(['photo'=>$filename]);
            }
        } catch (\Exception $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }
        return redirect()->back()->with('success', ' Listing successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //
        $listing = Listing::find($request->id);
        $this->storage->delete($listing->photo);
        $listing->delete();
        return redirect()->back()->with('success','Listing has been successfully been deleted');
    }
}

resources/views/listing/create.blade.php
@extends('layouts.app')

@section('content')
<section class="pager-sec bfr">
    <div class="container">
        <div class="pager-sec-details">
            <h3>
                Quick submission
            </h3>
            <ul>
                <li class="item">
                    <a href="{{ url('/')}}">Home</a>
                </li>
            </ul>
        </div>
        <!--pager-sec-details end-->
    </div>
</section>
<div class="card uper">
    <div class="card-header" style="background-color:#070f43;">
        <h3 style="color: white;font-size: 26px; text-align: center;">Welcome to Ogarent</h3>
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <section class="blog-standard section-padding">
            <div class="container">
                <div class="blog-single-details">
                    <div class="row">
                        <div class="col-lg-8 ">
                            <div class="blog-posts">
                                <div id="post-10" class="blog-single-post  post-10 page type-page status-publish hentry">
                                    <div class="post_info">
                                        <ul class="post-nfo">
                                            <li><i class="la la-calendar"></i>September 26, 2019</li>
                                            <li><i class="la la-comment-o"></i><a href="index.html#comment-form" title="Comment">No Comments</a></li>
                                        </ul>
                                        <h3><span class="ntitle"></span></h3>
                                        <div class="post-content clearfix">
                                            <p></p>
                                            <div class="selio_sw_win_wrapper">
                                                <div class="ci sw_widget sw_wrap">
                                                    <div class="bootstrap-wrapper quick-submission">
                                                        <div class="widget widget-styles clearfix" id="quick_submission_form">


                                                            <form action="{{ route('listing.store') }}" method="POST">
                                                                @csrf
                                                                <div class="row">
                                                                    <div class="col-xs-12 col-sm-12">
                                                                        <div class="form-group  IS-INPUTBOX ">
                                                                           
                                                                            <label for="name" class="control-label">Name</label>
                                                                            <div class="form-field">
                                                                                <input class="" id="name" name="name" type="text" value="" placeholder="The name of your Property" />
                                                                            </div>
                                                                        </div><!-- /.form-group -->

                                                                        <div class="form-group  IS-INPUTBOX ">
                                                                            <label for="location" class="control-label">Location</label>
                                                                            <div class="form-field">
                                                                                <input name="location" value="" type="text" id="location" class="" placeholder="Location of the house" />
                                                                            </div>
                                                                        </div>


                                                                        <div class="form-group  IS-INPUTBOX ">
                                                                            <div class="form-field col-md-6">
                                                                                <label for="bathroom" class="control-label">Bathroom</label>
                                                                                <input name="bathroom" value="" type="number" id="bathroom" class="" placeholder="Number of bathroom" />
                                                                            </div>
                                                                            <div class="form-field col-md-6">
                                                                                <label for="bedroom" class="control-label">Bedroom</label>
                                                                                <input name="bedroom" value="" type="number" id="bedroom" class="" placeholder="number of bedroom" />
                                                                            </div>
                                                                        </div>

                                                                        <div class="form-group  ">
                                                                            <label for="area" class="control-label">Area</label>
                                                                            <div class="form-field">
                                                                                <input name="area" type="text" id="area" class="" placeholder="youar area in map">
                                                                            </div>
                                                                        </div>
                                                                        <div class="form-group">
                                                                            <label for="garage" class="control-label">Garage</label>
                                                                            <select class="form-field" name="garage">
                                                                                <option value="yes" name="yes" id="yes">Yes</option>
                                                                                <option value="no" name="no" id="yes">No</option>
                                                                            </select>
                                                                        </div>

                                                                        <div class=" form-group  ">
                                                                            <label for="description" class="control-label">Description</label>
                                                                            <div class="form-field">
                                                                                <textarea class="area" rows="5" cols="40" name="description" id="description"></textarea>
                                                                            </div>
                                                                        </div>

                                                                        <div class="field_13 form-group  ">
                                                                            <label for="cooling" class="control-label">Cooling</label>
                                                                            <div class="form-field">
                                                                                <input type="text" name="cooling" placeholder="What kind of cooling system is available">
                                                                            </div>
                                                                        </div>

                                                                        <div class="field_13 form-group  ">
                                                                            <label for="map" class="control-label">Map</label>
                                                                            <div class="form-field">
                                                                                <input type="text" name="map" placeholder="map description">
                                                                            </div>
                                                                        </div>

                                                                        <div class="field_1 ">
                                                                            <hr />
                                                                            <h4>Overview</h4>
                                                                            <hr />
                                                                        </div>

                                                                        <div class="field_13 form-group  ">
                                                                            <label for="price" class="control-label">Sales Price</label>
                                                                            <div class="form-field">
                                                                                <input type="text" name="price" placeholder="price in naira">
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                                <hr class="mt15" />

                                                                <div class="fileupload-buttonbar celarfix" style="margin-top: 19px;">
                                                                    <div class="col-md-7">
                                                                        <!-- The fileinput-button span is used to style the file input field as button -->
                                                                        <span class="btn btn-success fileinput-button">
                                                                            <i class="icon-plus icon-white"></i>
                                                                            <span>Add files...</span>
                                                                            <input type="file" name="photo">
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                                <div class="form-group row">
                                                                    <div class="col-sm-offset-4">
                                                                        <button type="submit" class="btn-default">Save</button>
                                                                    </div>
                                                                </div>

                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>


                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card-border">
                                <div class="category_header" style="background-color: #070f43; height: 48px;">
                                    <h1 style="text-align: center; color: white;">Featured Listing</h1>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
            <!-- featured listing -->
    </div>





</div>
</div>
<p></p>
</div>
</div>
</div>
<!--blog-single-post end-->


</div>
<!--blog-posts end-->
</div>

</div>
</div>
<!--blog-single-details end-->
</div>
</section>
<!--blog-single-sec end-->
<div class="bottom-sidebar">
    <div id="widget-fullwidth-discover-1" class="widget-fullwidth-discover block-selio col-xl-3 col-sm-6 col-md-3"> <a href="#" title="Discover a home you&#8217;ll love to stay">
            <section class="cta st2 section-padding" style="background: #303e94;">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="cta-text">
                                <h2>Discover a home you&#8217;ll love to stay</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </a>

    </div> <!-- end widget -->
</div>




@endsection

resources/views/listing/index.blade.php
@extends('layout.app')xz/,

@section('content')

<!--  -->

<table class="table table-striped">
	<thead>
		<tr>
			<td>ID</td>
			<td>Name</td>
			<td>Location</td>
			<td>Bathroom</td>
			<td>Bedroom</td>
			<td>Area</td>
			<td>Garage</td>
			<td>Description</td>
			<td>Cooling</td>
			<td>Map</td>
			<td>Price</td>
			<td>Photo</td>
			<td colspan="2">Action</td>
		</tr>
	</thead>
<tbody>
@foreach ($listings as $listing)
<tr>
<td>{{ $listing->id }}</td>
<td>{{ $listing->name }}</td>
<td>{{ $listing->location }}</td>
<td>{{ $listing->bathroom }}</td>
<td>{{ $listing->bedroom }}</td>
<td>{{ $listing->area }}</td>
<td>{{ $listing->garage }}</td>
<td>{{ $listing->description }}</td>
<td>{{ $listing->cooling }}</td>
<td>{{ $listing->map }}</td>
<td>{{ $listing->price }}</td>
<td>{{ $listing->photo }}</td>
<td><a href="{{ route('listing.edit',$listing->id)}}"class="btn btn-primary">Edit</a></td>
<td>
<form action="{{ route('$listing.destroy',$listing->id)}}"method="post">
@csrf
@method('DELETE')
<buttonclass="btn btn-danger"type="submit">Delete</button>
</form>
</td>
</tr>
@endforeach
</tbody>
</table>
<div>
@endsection